# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'context_config_ui.ui'
##
## Created by: Qt User Interface Compiler version 6.4.0
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QAction, QBrush, QColor, QConicalGradient,
    QCursor, QFont, QFontDatabase, QGradient,
    QIcon, QImage, QKeySequence, QLinearGradient,
    QPainter, QPalette, QPixmap, QRadialGradient,
    QTransform)
from PySide6.QtWidgets import (QApplication, QGroupBox, QHBoxLayout, QHeaderView,
    QMainWindow, QMenu, QMenuBar, QSizePolicy,
    QSplitter, QStatusBar, QTextEdit, QVBoxLayout,
    QWidget)

from .widgets.context.table_view_channel import QTableViewChannelWidget
from .widgets.context.table_view_context import QTableViewContextWidget
from .widgets.context.tree_view_context import QTreeViewContextWidget

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1300, 700)
        icon = QIcon()
        icon.addFile(u":/context-edit.png", QSize(), QIcon.Normal, QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.actionImport = QAction(MainWindow)
        self.actionImport.setObjectName(u"actionImport")
        icon1 = QIcon()
        icon1.addFile(u"_imgs/local.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionImport.setIcon(icon1)
        self.actionToFile = QAction(MainWindow)
        self.actionToFile.setObjectName(u"actionToFile")
        icon2 = QIcon()
        icon2.addFile(u"_imgs/file-code.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionToFile.setIcon(icon2)
        self.actionSave = QAction(MainWindow)
        self.actionSave.setObjectName(u"actionSave")
        icon3 = QIcon()
        icon3.addFile(u"_imgs/save.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSave.setIcon(icon3)
        self.actionSaveAs = QAction(MainWindow)
        self.actionSaveAs.setObjectName(u"actionSaveAs")
        icon4 = QIcon()
        icon4.addFile(u"_imgs/save_as.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionSaveAs.setIcon(icon4)
        self.actionQuery = QAction(MainWindow)
        self.actionQuery.setObjectName(u"actionQuery")
        icon5 = QIcon()
        icon5.addFile(u"_imgs/database-search.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionQuery.setIcon(icon5)
        self.actionRefresh = QAction(MainWindow)
        self.actionRefresh.setObjectName(u"actionRefresh")
        icon6 = QIcon()
        icon6.addFile(u"_imgs/refresh.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionRefresh.setIcon(icon6)
        self.actionQueryAll = QAction(MainWindow)
        self.actionQueryAll.setObjectName(u"actionQueryAll")
        icon7 = QIcon()
        icon7.addFile(u"_imgs/database-download.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionQueryAll.setIcon(icon7)
        self.action_create_chip_line = QAction(MainWindow)
        self.action_create_chip_line.setObjectName(u"action_create_chip_line")
        self.action_init_base_qubit = QAction(MainWindow)
        self.action_init_base_qubit.setObjectName(u"action_init_base_qubit")
        icon8 = QIcon()
        icon8.addFile(u":/init_qubit.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_init_base_qubit.setIcon(icon8)
        self.action_init_config = QAction(MainWindow)
        self.action_init_config.setObjectName(u"action_init_config")
        icon9 = QIcon()
        icon9.addFile(u":/init_config.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_init_config.setIcon(icon9)
        self.action_clear = QAction(MainWindow)
        self.action_clear.setObjectName(u"action_clear")
        icon10 = QIcon()
        icon10.addFile(u":/clear.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_clear.setIcon(icon10)
        self.action_maximum = QAction(MainWindow)
        self.action_maximum.setObjectName(u"action_maximum")
        self.action_maximum.setCheckable(True)
        self.action_maximum.setChecked(False)
        self.action_minimum = QAction(MainWindow)
        self.action_minimum.setObjectName(u"action_minimum")
        self.action_minimum.setCheckable(True)
        self.action_minimum.setChecked(True)
        self.action_add_qubit = QAction(MainWindow)
        self.action_add_qubit.setObjectName(u"action_add_qubit")
        icon11 = QIcon()
        icon11.addFile(u":/qubit.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_add_qubit.setIcon(icon11)
        self.action_add_coupler = QAction(MainWindow)
        self.action_add_coupler.setObjectName(u"action_add_coupler")
        self.action_add_dcm = QAction(MainWindow)
        self.action_add_dcm.setObjectName(u"action_add_dcm")
        icon12 = QIcon()
        icon12.addFile(u":/dcm.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_add_dcm.setIcon(icon12)
        self.action_sq = QAction(MainWindow)
        self.action_sq.setObjectName(u"action_sq")
        self.action_sqc = QAction(MainWindow)
        self.action_sqc.setObjectName(u"action_sqc")
        self.action_add_inst = QAction(MainWindow)
        self.action_add_inst.setObjectName(u"action_add_inst")
        icon13 = QIcon()
        icon13.addFile(u":/inst.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_add_inst.setIcon(icon13)
        self.action_add_crosstalk = QAction(MainWindow)
        self.action_add_crosstalk.setObjectName(u"action_add_crosstalk")
        icon14 = QIcon()
        icon14.addFile(u":/crosstalk.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_add_crosstalk.setIcon(icon14)
        self.action_set_env_bit = QAction(MainWindow)
        self.action_set_env_bit.setObjectName(u"action_set_env_bit")
        icon15 = QIcon()
        icon15.addFile(u":/set_env_bit.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_set_env_bit.setIcon(icon15)
        self.action_add_compensate = QAction(MainWindow)
        self.action_add_compensate.setObjectName(u"action_add_compensate")
        icon16 = QIcon()
        icon16.addFile(u":/compensate.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_add_compensate.setIcon(icon16)
        self.action_create = QAction(MainWindow)
        self.action_create.setObjectName(u"action_create")
        icon17 = QIcon()
        icon17.addFile(u":/create_context.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_create.setIcon(icon17)
        self.action_reset_context = QAction(MainWindow)
        self.action_reset_context.setObjectName(u"action_reset_context")
        icon18 = QIcon()
        icon18.addFile(u":/refresh.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_reset_context.setIcon(icon18)
        self.action_cpqc = QAction(MainWindow)
        self.action_cpqc.setObjectName(u"action_cpqc")
        self.action_qntf = QAction(MainWindow)
        self.action_qntf.setObjectName(u"action_qntf")
        self.action_qnts = QAction(MainWindow)
        self.action_qnts.setObjectName(u"action_qnts")
        self.action_crosstalk = QAction(MainWindow)
        self.action_crosstalk.setObjectName(u"action_crosstalk")
        self.action_chip_layout = QAction(MainWindow)
        self.action_chip_layout.setObjectName(u"action_chip_layout")
        self.action_chip_layout.setIcon(icon9)
        self.action_save_line = QAction(MainWindow)
        self.action_save_line.setObjectName(u"action_save_line")
        icon19 = QIcon()
        icon19.addFile(u":/save.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_save_line.setIcon(icon19)
        self.actionStandardContext = QAction(MainWindow)
        self.actionStandardContext.setObjectName(u"actionStandardContext")
        icon20 = QIcon()
        icon20.addFile(u":/build.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionStandardContext.setIcon(icon20)
        self.action_sync_chip_Line = QAction(MainWindow)
        self.action_sync_chip_Line.setObjectName(u"action_sync_chip_Line")
        icon21 = QIcon()
        icon21.addFile(u":/reset.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_sync_chip_Line.setIcon(icon21)
        self.action_delete_init_config = QAction(MainWindow)
        self.action_delete_init_config.setObjectName(u"action_delete_init_config")
        icon22 = QIcon()
        icon22.addFile(u":/delete2.png", QSize(), QIcon.Normal, QIcon.Off)
        self.action_delete_init_config.setIcon(icon22)
        self.action_del_and_init_qubit = QAction(MainWindow)
        self.action_del_and_init_qubit.setObjectName(u"action_del_and_init_qubit")
        self.action_del_and_init_qubit.setIcon(icon22)
        self.actionInit_sos_RT_data = QAction(MainWindow)
        self.actionInit_sos_RT_data.setObjectName(u"actionInit_sos_RT_data")
        icon23 = QIcon()
        icon23.addFile(u":/config.png", QSize(), QIcon.Normal, QIcon.Off)
        self.actionInit_sos_RT_data.setIcon(icon23)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.horizontalLayout_2 = QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName(u"horizontalLayout_2")
        self.widget_2 = QWidget(self.centralwidget)
        self.widget_2.setObjectName(u"widget_2")
        self.verticalLayout_2 = QVBoxLayout(self.widget_2)
        self.verticalLayout_2.setObjectName(u"verticalLayout_2")
        self.verticalLayout_2.setContentsMargins(0, 0, 5, 0)
        self.groupBox = QGroupBox(self.widget_2)
        self.groupBox.setObjectName(u"groupBox")
        self.horizontalLayout = QHBoxLayout(self.groupBox)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setContentsMargins(0, 6, 0, 0)
        self.table_view_channel = QTableViewChannelWidget(self.groupBox)
        self.table_view_channel.setObjectName(u"table_view_channel")

        self.horizontalLayout.addWidget(self.table_view_channel)


        self.verticalLayout_2.addWidget(self.groupBox)

        self.groupBox_2 = QGroupBox(self.widget_2)
        self.groupBox_2.setObjectName(u"groupBox_2")
        self.horizontalLayout_3 = QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName(u"horizontalLayout_3")
        self.horizontalLayout_3.setContentsMargins(0, 6, 0, 0)
        self.table_view_context = QTableViewContextWidget(self.groupBox_2)
        self.table_view_context.setObjectName(u"table_view_context")

        self.horizontalLayout_3.addWidget(self.table_view_context)


        self.verticalLayout_2.addWidget(self.groupBox_2)


        self.horizontalLayout_2.addWidget(self.widget_2)

        self.groupBox_3 = QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName(u"groupBox_3")
        self.verticalLayout = QVBoxLayout(self.groupBox_3)
        self.verticalLayout.setObjectName(u"verticalLayout")
        self.splitter = QSplitter(self.groupBox_3)
        self.splitter.setObjectName(u"splitter")
        self.splitter.setOrientation(Qt.Vertical)
        self.tree_view_context = QTreeViewContextWidget(self.splitter)
        self.tree_view_context.setObjectName(u"tree_view_context")
        self.splitter.addWidget(self.tree_view_context)
        self.textEdit = QTextEdit(self.splitter)
        self.textEdit.setObjectName(u"textEdit")
        self.splitter.addWidget(self.textEdit)

        self.verticalLayout.addWidget(self.splitter)


        self.horizontalLayout_2.addWidget(self.groupBox_3)

        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(MainWindow)
        self.statusbar.setObjectName(u"statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menuBar = QMenuBar(MainWindow)
        self.menuBar.setObjectName(u"menuBar")
        self.menuBar.setGeometry(QRect(0, 0, 1300, 22))
        self.menuChip = QMenu(self.menuBar)
        self.menuChip.setObjectName(u"menuChip")
        self.menuContext = QMenu(self.menuBar)
        self.menuContext.setObjectName(u"menuContext")
        self.menuStandard = QMenu(self.menuBar)
        self.menuStandard.setObjectName(u"menuStandard")
        MainWindow.setMenuBar(self.menuBar)

        self.menuBar.addAction(self.menuChip.menuAction())
        self.menuBar.addAction(self.menuContext.menuAction())
        self.menuBar.addAction(self.menuStandard.menuAction())
        self.menuChip.addAction(self.action_chip_layout)
        self.menuChip.addAction(self.action_save_line)
        self.menuChip.addAction(self.action_sync_chip_Line)
        self.menuChip.addSeparator()
        self.menuChip.addAction(self.action_init_base_qubit)
        self.menuChip.addAction(self.action_init_config)
        self.menuChip.addSeparator()
        self.menuChip.addAction(self.action_del_and_init_qubit)
        self.menuChip.addAction(self.action_delete_init_config)
        self.menuChip.addSeparator()
        self.menuChip.addAction(self.actionInit_sos_RT_data)
        self.menuContext.addAction(self.action_create)
        self.menuContext.addAction(self.action_set_env_bit)
        self.menuContext.addSeparator()
        self.menuContext.addAction(self.action_add_inst)
        self.menuContext.addAction(self.action_add_qubit)
        self.menuContext.addAction(self.action_add_dcm)
        self.menuContext.addAction(self.action_add_crosstalk)
        self.menuContext.addAction(self.action_add_compensate)
        self.menuContext.addSeparator()
        self.menuContext.addAction(self.action_minimum)
        self.menuContext.addAction(self.action_maximum)
        self.menuContext.addSeparator()
        self.menuContext.addAction(self.action_clear)
        self.menuContext.addAction(self.action_reset_context)
        self.menuStandard.addAction(self.actionStandardContext)

        self.retranslateUi(MainWindow)
        self.action_add_compensate.triggered.connect(MainWindow.context_add_compensates)
        self.action_add_crosstalk.triggered.connect(MainWindow.context_add_crosstalk)
        self.action_add_dcm.triggered.connect(MainWindow.context_add_dcm)
        self.action_add_inst.triggered.connect(MainWindow.context_add_inst)
        self.action_add_qubit.triggered.connect(MainWindow.context_add_qubit)
        self.action_clear.triggered.connect(MainWindow.context_clear)
        self.action_create.triggered.connect(MainWindow.context_create)
        self.action_init_config.triggered.connect(MainWindow.chip_init_config_data)
        self.action_set_env_bit.triggered.connect(MainWindow.context_set_env_bit)
        self.action_init_base_qubit.triggered.connect(MainWindow.chip_init_base_qubit)
        self.action_reset_context.triggered.connect(MainWindow.context_reset)
        self.action_minimum.triggered.connect(MainWindow.context_min_env)
        self.action_maximum.triggered.connect(MainWindow.context_max_env)
        self.action_chip_layout.triggered.connect(MainWindow.chip_layout)
        self.action_save_line.triggered.connect(MainWindow.chip_save_line)
        self.actionStandardContext.triggered.connect(MainWindow.build_std_context)
        self.action_sync_chip_Line.triggered.connect(MainWindow.sync_chip_line)
        self.action_delete_init_config.triggered.connect(MainWindow.chip_del_init_config_data)
        self.action_del_and_init_qubit.triggered.connect(MainWindow.chip_del_init_qubit_data)
        self.actionInit_sos_RT_data.triggered.connect(MainWindow.chip_init_sos_rt_data)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"Context Editor", None))
        self.actionImport.setText(QCoreApplication.translate("MainWindow", u"Import", None))
        self.actionToFile.setText(QCoreApplication.translate("MainWindow", u"ToFile", None))
        self.actionSave.setText(QCoreApplication.translate("MainWindow", u"Save", None))
        self.actionSaveAs.setText(QCoreApplication.translate("MainWindow", u"SaveAs", None))
        self.actionQuery.setText(QCoreApplication.translate("MainWindow", u"Query", None))
        self.actionRefresh.setText(QCoreApplication.translate("MainWindow", u"Refresh", None))
        self.actionQueryAll.setText(QCoreApplication.translate("MainWindow", u"QueryAll", None))
#if QT_CONFIG(tooltip)
        self.actionQueryAll.setToolTip(QCoreApplication.translate("MainWindow", u"Query All Qubit", None))
#endif // QT_CONFIG(tooltip)
        self.action_create_chip_line.setText(QCoreApplication.translate("MainWindow", u"Create Chip Line", None))
        self.action_init_base_qubit.setText(QCoreApplication.translate("MainWindow", u"Init Base Qubit", None))
        self.action_init_config.setText(QCoreApplication.translate("MainWindow", u"Init Config Data", None))
        self.action_clear.setText(QCoreApplication.translate("MainWindow", u"Clear Context", None))
        self.action_maximum.setText(QCoreApplication.translate("MainWindow", u"maximum", None))
        self.action_minimum.setText(QCoreApplication.translate("MainWindow", u"minimum", None))
        self.action_add_qubit.setText(QCoreApplication.translate("MainWindow", u"Add Qubit", None))
        self.action_add_coupler.setText(QCoreApplication.translate("MainWindow", u"Add Coupler", None))
        self.action_add_dcm.setText(QCoreApplication.translate("MainWindow", u"Add Dcm", None))
        self.action_sq.setText(QCoreApplication.translate("MainWindow", u"sinle_base_qubit", None))
        self.action_sqc.setText(QCoreApplication.translate("MainWindow", u"single_qubit_calibration", None))
        self.action_add_inst.setText(QCoreApplication.translate("MainWindow", u"Add Inst", None))
        self.action_add_crosstalk.setText(QCoreApplication.translate("MainWindow", u"Add Crosstalk", None))
        self.action_set_env_bit.setText(QCoreApplication.translate("MainWindow", u"Set Env Bit", None))
        self.action_add_compensate.setText(QCoreApplication.translate("MainWindow", u"Add Compensate", None))
        self.action_create.setText(QCoreApplication.translate("MainWindow", u"Create Context", None))
        self.action_reset_context.setText(QCoreApplication.translate("MainWindow", u"Reset Context ", None))
        self.action_cpqc.setText(QCoreApplication.translate("MainWindow", u"coupler_probe_qubit_calibration", None))
        self.action_qntf.setText(QCoreApplication.translate("MainWindow", u"qubit_net_tunable_first", None))
        self.action_qnts.setText(QCoreApplication.translate("MainWindow", u"qubit_net_tunable_second", None))
        self.action_crosstalk.setText(QCoreApplication.translate("MainWindow", u"ac_crosstalk_env", None))
        self.action_chip_layout.setText(QCoreApplication.translate("MainWindow", u"Chip Layout", None))
        self.action_save_line.setText(QCoreApplication.translate("MainWindow", u"Save Chip Line", None))
        self.actionStandardContext.setText(QCoreApplication.translate("MainWindow", u"Standard Context", None))
#if QT_CONFIG(shortcut)
        self.actionStandardContext.setShortcut(QCoreApplication.translate("MainWindow", u"Ctrl+Alt+B", None))
#endif // QT_CONFIG(shortcut)
        self.action_sync_chip_Line.setText(QCoreApplication.translate("MainWindow", u"Sync Chip Line", None))
        self.action_delete_init_config.setText(QCoreApplication.translate("MainWindow", u"del and init config", None))
        self.action_del_and_init_qubit.setText(QCoreApplication.translate("MainWindow", u"del and init Qubit", None))
        self.actionInit_sos_RT_data.setText(QCoreApplication.translate("MainWindow", u"Init sos RT data", None))
        self.groupBox.setTitle(QCoreApplication.translate("MainWindow", u"Chip Bit Channel", None))
        self.groupBox_2.setTitle(QCoreApplication.translate("MainWindow", u"Context Collector", None))
        self.groupBox_3.setTitle(QCoreApplication.translate("MainWindow", u"Component", None))
        self.menuChip.setTitle(QCoreApplication.translate("MainWindow", u"Chip", None))
        self.menuContext.setTitle(QCoreApplication.translate("MainWindow", u"Context", None))
        self.menuStandard.setTitle(QCoreApplication.translate("MainWindow", u"Standard", None))
    # retranslateUi

